apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
        - name: PORT
          value: "5002"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: jwt_secret
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: mongo_uri
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
