apiVersion: v1
kind: Secret
metadata:
  name: product-secret
type: Opaque
data:
  # echo -n "super_secret_jwt_key_for_auth_development" | base64
  jwt_secret: c3VwZXJfc2VjcmV0X2p3dF9rZXlfZm9yX2F1dGg= 
  # echo -n "mongodb://mongodb-service:27017/product-db" | base64
  mongo_uri: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9wcm9kdWN0LWRi
