apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    {{- include "product-service.labels" . | nindent 4 }}
spec:
  selector: { app.kubernetes.io/name: product-service }
  ports: [{ name: http, port: 5002, targetPort: http }]
