apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  # Values must be base64 encoded
  # echo -n "your_secret_key" | base64
  jwt_secret: c3VwZXJfc2VjcmV0X2p3dF9rZXlfZm9yX2F1dGg= 
  # echo -n "mongodb://mongodb-service:27017/auth-db" | base64
  mongo_uri: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9hdXRoLWRi
